baseURL = 'https://czaree.github.io/bingo.maker/'
locale = 'en-us'
title = 'bingo.maker'
theme = 'hugo-classless'
description = "make bingo cards from a word bank, then roll a card and start playing!"
[Params]
    author = "czaree"
    github = "czaree"
    themeBase = "css/base.css"
    themeLight = "css/light.css"
    themeDark = "css/dark.css"
[[menus.main]]
    name = "Home"
    pageRef = "/"
    weight = 1
[[menus.main]]
    name = "Create"
    pageRef = "/create/"
    weight = 2
[[menus.main]]
    name = "About"
    pageRef = "/about/"
    weight = 3