baseURL = '/'
locale = 'en-us'
title = 'bingo.maker'
theme = 'kube'
description = "make bingo cards from a word bank, then roll a card and start playing!"
[Params]
author = "czaree"
github = "czaree"

[[menus.main]]
    name = "Home"
    pageRef = "/"
    weight = 1
[[menus.main]]
    name = "Create"
    pageRef = "/create/"
    weight = 2
[[menus.main]]
    name = "Play"
    pageRef = "/play/"
    weight = 3